-- Cleanup MySQL Demo
USE ROLE ACCOUNTADMIN;

DROP SERVICE IF EXISTS SNOWFLAKE_PROD_USER2.NIFI_DEMO.MYSQL_SERVICE;

USE DATABASE SNOWFLAKE_PROD_USER2;
USE SCHEMA NIFI_DEMO;

DROP TABLE IF EXISTS MYSQL_CUSTOMERS;
DROP TABLE IF EXISTS MYSQL_PRODUCTS;

SELECT 'MySQL demo cleanup complete!' AS STATUS;
