-- Setup MySQL Demo Tables
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_PROD_USER2;
USE SCHEMA NIFI_DEMO;

CREATE TABLE IF NOT EXISTS MYSQL_CUSTOMERS (
    ID INT,
    CUSTOMER_ID VARCHAR(50),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    EMAIL VARCHAR(255),
    PHONE VARCHAR(50),
    CITY VARCHAR(100),
    COUNTRY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE TABLE IF NOT EXISTS MYSQL_PRODUCTS (
    ID INT,
    PRODUCT_ID VARCHAR(50),
    PRODUCT_NAME VARCHAR(255),
    CATEGORY VARCHAR(100),
    PRICE DECIMAL(10,2),
    STOCK_QUANTITY INT,
    IS_ACTIVE BOOLEAN,
    CREATED_AT TIMESTAMP_NTZ,
    UPDATED_AT TIMESTAMP_NTZ,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

SELECT 'MySQL demo tables created!' AS STATUS;
