-- Cleanup Streamlit Demo
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_PROD_USER2;
USE SCHEMA NIFI_DEMO;

DROP STREAMLIT IF EXISTS NIFI_DEMO_DASHBOARD;

SELECT 'Streamlit demo cleanup complete!' AS STATUS;
