-- Cleanup Kafka Demo
USE ROLE ACCOUNTADMIN;

DROP SERVICE IF EXISTS SNOWFLAKE_PROD_USER2.NIFI_DEMO.DATA_GENERATOR_SERVICE;
DROP SERVICE IF EXISTS SNOWFLAKE_PROD_USER2.NIFI_DEMO.KAFKA_SERVICE;

USE DATABASE SNOWFLAKE_PROD_USER2;
USE SCHEMA NIFI_DEMO;

DROP TABLE IF EXISTS KAFKA_ORDERS;
DROP TABLE IF EXISTS KAFKA_EVENTS;

SELECT 'Kafka demo cleanup complete!' AS STATUS;
