-- Setup Kafka Demo Tables
USE ROLE ACCOUNTADMIN;
USE DATABASE SNOWFLAKE_PROD_USER2;
USE SCHEMA NIFI_DEMO;

-- Kafka Orders Table
CREATE TABLE IF NOT EXISTS KAFKA_ORDERS (
    ORDER_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    ORDER_DATE TIMESTAMP_NTZ,
    TOTAL_AMOUNT DECIMAL(12, 2),
    STATUS VARCHAR(50),
    ITEMS VARIANT,
    PAYMENT_METHOD VARCHAR(50),
    SHIPPING_CITY VARCHAR(100),
    KAFKA_OFFSET BIGINT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_MESSAGE VARIANT
);

-- Kafka Events Table
CREATE TABLE IF NOT EXISTS KAFKA_EVENTS (
    EVENT_ID VARCHAR(50),
    EVENT_TYPE VARCHAR(100),
    EVENT_TIME TIMESTAMP_NTZ,
    USER_ID VARCHAR(50),
    SESSION_ID VARCHAR(100),
    PAGE_URL VARCHAR(500),
    DEVICE_TYPE VARCHAR(50),
    PROPERTIES VARIANT,
    KAFKA_OFFSET BIGINT,
    INGESTION_TIME TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    RAW_MESSAGE VARIANT
);

SELECT 'Kafka demo tables created!' AS STATUS;
